### PR TITLE
Merge user-interface with development branch

### PR DESCRIPTION
**Pull request by Greg0109**
Changelog:
- Added user interface

### CODE REVIEW

**Comment by descholar-ceo** [comment]
# This Pull Request is under review by [descholar-ceo](https://github.com/descholar-ceo) :eyes: :eyes: 
## Please wait a bit ...

**Review by descholar-ceo — CHANGES_REQUESTED** [review]
# Status: Changes Required :vertical_traffic_light: :warning: 
## Hello @Greg0109 and @billodiallo  :handshake: :handshake: :handshake: 

:+1: This is good to make it this far, your project is really nice, congratulations on the good work you have done so far.
:+1: I liked that you have tried to implement all of the minimum requirements of this project, keep it up, and your project is really almost done.
#### :warning: However we need to make few changes to mark this project approved. See the requested change below :point_down: :point_down: :point_down: 
### Note: All of requested changes which are marked as [Required] are mandatory to be implemented in order to get this project approved, others which are marked as [Optional] are nice to have in your project to make it outstanding

# [Required Changes] :red_circle: 

## Behavior requirements
=> Almost all the basic flow has been implemented, but there are some which are missing
- [x] game informs player if the selected move is invalid (without computing what an invalid move is)
- [x] game informs player if the selected move is a winning move (without computing the winning move)
- [x] game informs player if the selected move is a draw move (without computing draw)
- [x] game repeats all actions for the next player's move
- [x] A loop needs to be terminated at some point (after a winning move or draw to be more specific). It can be done with variable:
```ruby

game_on = true

# initial instructions for player

while game_on
  # loop for each move

  if winner # and/or draw (the exact condition in this milestone is not important)
    game_on = false
  end
end
```
# [Optional changes] :yellow_circle: 
- [ ] game asks players for their names
___
_If anything seems to be unclear to you, reachout and ask anything by commenting on this Pull Request and mention me as [descholar-ceo](https://github.com/descholar-ceo), I will receive a notification and will respond._

[GitHub](https://github.com/descholar-ceo) | [LinkedIn](https://linkedin.com/in/mugirase-emmanuel) | [Twitter](https://twitter.com/descholar3)

_Reviewed by [Mugirase Emmanuel (descholar)](https://github.com/descholar-ceo)_

**Comment by Greg0109** [comment]
I am afraid you are mistaken, this pull request is only for the User interface, not the game logic, all those changes you are requesting are on the game logic branch, which cannot be reviewed until the user interface branch is reviewed. 

This branch is supposed to have only the user interface, with no game logic

**Comment by descholar-ceo** [comment]
> I am afraid you are mistaken, this pull request is only for the User interface, not the game logic, all those changes you are requesting are on the game logic branch, which cannot be reviewed until the user interface branch is reviewed.
> 
> This branch is supposed to have only the user interface, with no game logic

Hello @Greg0109 , thank you for reaching out for more clarification, 

Actually those points I highlighted, should be displayed on the screen (_without implementing their logic_). The system needs to have all of those, actually this milestone is kind of confusing for most students, but think it as a planning step of the milestone 3. So, take your time and think of all of the steps needed in game logic, and display all of those steps on the screen (without computing them). And then submit another code review request.

## Note: Thake it easy, you just need to display messages, and show those steps, so that the next milestone will be very easy for you to implement it!

Happy coding!

**Comment by Greg0109** [comment]
The third milestone is finished with all the methods implemented, I'm just waiting on getting this one approved so I can submit the third milestone

**Comment by descholar-ceo** [comment]
> The third milestone is finished with all the methods implemented, I'm just waiting on getting this one approved so I can submit the third milestone

@Greg0109 That is very good and I really apreciate the courage and effort you put into this project. Keep that up. However this milestone also needs to be implemented as its specifications state it.

**Review by descholar-ceo — CHANGES_REQUESTED** [review]
# Status: Changes Required :vertical_traffic_light: :warning: 
## Hello @Greg0109 and @billodiallo  :handshake: :handshake: :handshake: 

# [Required Changes] :red_circle: 
- [x] Ensure that you implement all of the requested [required] changes in the previous review
___
_If anything seems to be unclear to you, reachout and ask anything by commenting on this Pull Request and mention me as [descholar-ceo](https://github.com/descholar-ceo), I will receive a notification and will respond._

[GitHub](https://github.com/descholar-ceo) | [LinkedIn](https://linkedin.com/in/mugirase-emmanuel) | [Twitter](https://twitter.com/descholar3)

_Reviewed by [Mugirase Emmanuel (descholar)](https://github.com/descholar-ceo)_

**Comment by Greg0109** [comment]
Requested changes done [descholar-ceo](https://github.com/descholar-ceo)

**Review by descholar-ceo — APPROVED** [review]
# Status: Approved :heavy_check_mark: :heavy_check_mark: :heavy_check_mark:  
## :clap: :clap: :clap: Congratulations @Greg0109 and @billodiallo  , your project is approved :tada: :tada: :tada: 
You have implemented all minimum requirements for this project to mark it as complete, it doesn't need more changes, you can go ahead and merge all of the changes on base branch,

Don't forget to fill the mandatory project completion form, and see you to next project,

Happy coding :computer: :computer: :computer: 

Re-reviewed by [Mugirase Emmanuel (descholar)](https://github.com/descholar-ceo)

**Pull request merged**
